import * as economyConfig from '../../shared/economy-config.mjs';

const config = economyConfig as Record<string, any>;

export const GAME_ECONOMY_VERSION = config.GAME_ECONOMY_VERSION;

export const STARTING_COINS = config.STARTING_COINS;
export const DAILY_FREE_BAIT = config.DAILY_FREE_BAIT;
export const WALLET_CONNECT_BAIT_BONUS = config.WALLET_CONNECT_BAIT_BONUS;
export const REFERRAL_BAIT_BONUS = config.REFERRAL_BAIT_BONUS;
export const MAX_REWARDED_REFERRALS = config.MAX_REWARDED_REFERRALS;
export const MAX_EXTRA_BAIT_FROM_DAILIES_PER_DAY = config.MAX_EXTRA_BAIT_FROM_DAILIES_PER_DAY;
export const TARGET_PAID_BAIT_RTP = config.TARGET_PAID_BAIT_RTP;

export const XP_PER_LEVEL = config.XP_PER_LEVEL;
export const LEVEL_UP_COIN_REWARD_PER_LEVEL = config.LEVEL_UP_COIN_REWARD_PER_LEVEL;
export const CATCH_CHANCE = config.CATCH_CHANCE;
export const MISS_XP_REWARD = config.MISS_XP_REWARD;
export const CATCH_XP_FLAT_BONUS = config.CATCH_XP_FLAT_BONUS;
export const BAIT_COST = config.BAIT_COST;

export const BAIT_PACKAGES = config.BAIT_PACKAGES;

export const MON_MARKET_RECEIVER_ADDRESS = config.MON_MARKET_RECEIVER_ADDRESS;
export const WALLET_CHECK_IN_COST_MON = config.WALLET_CHECK_IN_COST_MON;
export const MON_HOLD_DAYS = config.MON_HOLD_DAYS;
export const MIN_WITHDRAW_MON = config.MIN_WITHDRAW_MON;

export const MON_COIN_PACKAGES = config.MON_COIN_PACKAGES;
export const MON_FISHING_NET_PACKAGES = config.MON_FISHING_NET_PACKAGES;
export const FISHING_NET_PRICE_COINS = config.FISHING_NET_PRICE_COINS;
export const FISHING_NET_DAILY_FISH_COUNT = config.FISHING_NET_DAILY_FISH_COUNT;
export const FISHING_NET_PAYBACK_DAYS_ESTIMATE = config.FISHING_NET_PAYBACK_DAYS_ESTIMATE;
export const MON_CUBE_SPIN_PACKAGES = config.MON_CUBE_SPIN_PACKAGES;

export const FISH_ECONOMY = config.FISH_ECONOMY;
export const FISH_DATA = config.FISH_DATA;

export const ROD_ECONOMY = config.ROD_ECONOMY;
export const ROD_DATA = config.ROD_DATA;
export const ROD_CUBE_DROP_CONFIG = config.ROD_CUBE_DROP_CONFIG;
export const LEVIATHAN_COMMON_ROD_BONUS_CONFIG = config.LEVIATHAN_COMMON_ROD_BONUS_CONFIG;

export const NFT_ROD_DATA = config.NFT_ROD_DATA;
export const NFT_ROD_BONUSES = config.NFT_ROD_BONUSES;

export const ALBUM_FIRST_CATCH_BONUSES = config.ALBUM_FIRST_CATCH_BONUSES;
export const COLLECTION_BOOK_PAGES = config.COLLECTION_BOOK_PAGES;

export const WHEEL_PRIZES = config.WHEEL_PRIZES;

export const DAILY_TASK_TARGETS = config.DAILY_TASK_TARGETS;
export const SPECIAL_TASK_TARGETS = config.SPECIAL_TASK_TARGETS;
export const DAILY_TASK_REWARDS = config.DAILY_TASK_REWARDS;
export const SPECIAL_TASK_REWARDS = config.SPECIAL_TASK_REWARDS;
export const WEEKLY_MISSION_CONFIG = config.WEEKLY_MISSION_CONFIG;
export const WEEKLY_MISSION_TARGETS = config.WEEKLY_MISSION_TARGETS;
export const WEEKLY_MISSION_REWARDS = config.WEEKLY_MISSION_REWARDS;
export const TASK_REWARDS = config.TASK_REWARDS;
export const DAILY_CLAIMS_FOR_CUBE = config.DAILY_CLAIMS_FOR_CUBE;
export const DAILY_CUBE_ROLL_REWARD = config.DAILY_CUBE_ROLL_REWARD;
export const SOCIAL_TASKS = config.SOCIAL_TASKS;
export const SOCIAL_TASK_REWARDS = config.SOCIAL_TASK_REWARDS;

export const GRILL_RECIPES = config.GRILL_RECIPES;

export const PREMIUM_SESSION_COST_MON = config.PREMIUM_SESSION_COST_MON;
export const PREMIUM_SESSION_CASTS = config.PREMIUM_SESSION_CASTS;
export const PREMIUM_SESSION_CONSUMES_BAIT = config.PREMIUM_SESSION_CONSUMES_BAIT;
export const PREMIUM_SESSION_BONUS_COINS_PER_CAST = config.PREMIUM_SESSION_BONUS_COINS_PER_CAST;
export const PREMIUM_SESSION_BONUS_XP_PER_CAST = config.PREMIUM_SESSION_BONUS_XP_PER_CAST;
export const PREMIUM_SESSION_ALBUM_POINTS_PER_CAST = config.PREMIUM_SESSION_ALBUM_POINTS_PER_CAST;
export const PREMIUM_SESSION_ROD_MASTERY_POINTS_PER_CAST = config.PREMIUM_SESSION_ROD_MASTERY_POINTS_PER_CAST;
export const PREMIUM_FISH_IDS = config.PREMIUM_FISH_IDS;
export const PREMIUM_MON_DROP_TABLE = config.PREMIUM_MON_DROP_TABLE;
export const PREMIUM_LUCK_METER_CONFIG = config.PREMIUM_LUCK_METER_CONFIG;
export const PREMIUM_PITY_CONFIG = config.PREMIUM_PITY_CONFIG;
export const PREMIUM_RESCUE_CONFIG = config.PREMIUM_RESCUE_CONFIG;
export const PREMIUM_FISH_WEIGHT_MODIFIERS = config.PREMIUM_FISH_WEIGHT_MODIFIERS;

export const WEEKLY_GRILL_PAYOUT_CONFIG = config.WEEKLY_GRILL_PAYOUT_CONFIG;
export const CUBE_REBALANCE_CONFIG = config.CUBE_REBALANCE_CONFIG;
