// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';
const SAME_ORIGIN_EDGE_PROXY_HOSTS = new Set(['www.hookloot.xyz']);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

const originalInvoke = supabaseClient.functions.invoke.bind(supabaseClient.functions);

const shouldUseSameOriginEdgeProxy = () => (
  typeof window !== 'undefined' && SAME_ORIGIN_EDGE_PROXY_HOSTS.has(window.location.hostname)
);

interface EdgeInvokeOptions {
  body?: unknown;
  headers?: HeadersInit;
  method?: string;
}

interface EdgeFunctionErrorContext {
  clone: () => Response;
}

export interface EdgeFunctionHttpError extends Error {
  context: EdgeFunctionErrorContext;
  status: number;
  responseBody: string;
  responseData: unknown;
}

const isMissingAuthHeaderProxyError = (error: unknown) => {
  if (!error || typeof error !== 'object') return false;

  const edgeError = error as Partial<EdgeFunctionHttpError>;
  if (edgeError.status !== 401) return false;

  const payload = edgeError.responseData;
  if (payload && typeof payload === 'object') {
    const code = typeof (payload as { code?: unknown }).code === 'string'
      ? (payload as { code: string }).code
      : '';
    const message = typeof (payload as { message?: unknown }).message === 'string'
      ? (payload as { message: string }).message
      : '';

    if (code === 'UNAUTHORIZED_NO_AUTH_HEADER') return true;
    if (message.toLowerCase().includes('missing authorization header')) return true;
  }

  return typeof edgeError.responseBody === 'string'
    && edgeError.responseBody.toLowerCase().includes('missing authorization header');
};

const buildInvokeBody = (body: unknown): BodyInit | undefined => {
  if (body == null) return undefined;
  if (
    typeof body === 'string'
    || body instanceof Blob
    || body instanceof FormData
    || body instanceof URLSearchParams
    || body instanceof ReadableStream
    || body instanceof ArrayBuffer
  ) {
    return body;
  }

  return JSON.stringify(body);
};

const buildInvokeHeaders = (body: unknown, initialHeaders?: HeadersInit) => {
  const headers = new Headers(initialHeaders ?? {});
  if (!headers.has('Content-Type') && body != null && !(body instanceof FormData)) {
    headers.set('Content-Type', 'application/json');
  }
  if (!headers.has('apikey')) {
    headers.set('apikey', SUPABASE_PUBLISHABLE_KEY);
  }
  if (!headers.has('Authorization')) {
    headers.set('Authorization', `Bearer ${SUPABASE_PUBLISHABLE_KEY}`);
  }
  return headers;
};

const buildInvokeUrl = (functionName: string) => (
  shouldUseSameOriginEdgeProxy()
    ? `/api/edge/${functionName}`
    : `${SUPABASE_URL}/functions/v1/${functionName}`
);

const parseResponsePayload = (response: Response, responseBody: string) => {
  if (response.status === 204 || !responseBody) return null;

  const contentType = response.headers.get('content-type') ?? '';
  if (contentType.includes('application/json')) {
    try {
      return JSON.parse(responseBody);
    } catch {
      return responseBody;
    }
  }

  return responseBody;
};

const buildErrorContext = (response: Response, responseBody: string): EdgeFunctionErrorContext => ({
  clone: () => new Response(responseBody, {
    status: response.status,
    statusText: response.statusText,
    headers: new Headers(response.headers),
  }),
});

export const invokeEdgeFunctionHttp = async <T>(
  functionName: string,
  options?: EdgeInvokeOptions,
): Promise<T> => {
  const response = await fetch(buildInvokeUrl(functionName), {
    method: options?.method ?? 'POST',
    headers: buildInvokeHeaders(options?.body, options?.headers),
    body: buildInvokeBody(options?.body),
  });

  const responseBody = response.status === 204 ? '' : await response.text();
  const responseData = parseResponsePayload(response, responseBody);

  if (!response.ok) {
    const error = Object.assign(
      new Error('Edge Function returned a non-2xx status code'),
      {
        context: buildErrorContext(response, responseBody),
        status: response.status,
        responseBody,
        responseData,
      },
    ) as EdgeFunctionHttpError;

    throw error;
  }

  return responseData as T;
};

(supabaseClient.functions as typeof supabaseClient.functions & {
  invoke: typeof originalInvoke;
}).invoke = (async (functionName: string, options?: {
  body?: unknown;
  headers?: HeadersInit;
  method?: string;
}) => {
  if (!shouldUseSameOriginEdgeProxy()) {
    return originalInvoke(functionName, options as Parameters<typeof originalInvoke>[1]);
  }

  try {
    const data = await invokeEdgeFunctionHttp(functionName, options);
    return { data, error: null };
  } catch (error) {
    if (isMissingAuthHeaderProxyError(error)) {
      return originalInvoke(functionName, options as Parameters<typeof originalInvoke>[1]);
    }

    return {
      data: null,
      error: error instanceof Error
        ? error
        : new Error('Edge Function returned a non-2xx status code'),
    };
  }
}) as typeof originalInvoke;

export const supabase = supabaseClient;
